### ISSUE TITLE
Change the font of the index page to Arial 

### ISSUE THREAD

**Issue by tejas-44** [tejas-44/sdg-fypm-final#1]
The font used is default font, change the font of the form to Arial.

**Comment by ManishINN** [comment]
Please tell me details ,
which place change fonts or screen shoot !

**Comment by tejas-44** [comment]
> Please tell me details ,
> which place change fonts or screen shoot !

Hey if you are registered as a participant at https://csirait.in/opencode/
you must have got a mail where there is the discord invite for the OpenCode server, there you will get all the announcement.
If you have any doubts related to any issues of this project, we can chat in the text channel allotted to this project there in the discord sever.
Moreover I think the contribution phase starts from tomorrow.

**Comment by Yuji-Itadorii** [comment]
hey @tejas-44, I am a participant in the open-code program. Please assign this issue to me.

**Comment by tejas-44** [comment]
> hey @tejas-44, I am a participant in the open-code program. Please assign this issue to me.

Hello Abhay, sorry to say but we're currently assigning one issue at a time. Once you complete your previously assigned issue I will assign this to you.

**Comment by surjyaneeh** [comment]
I am a participant in the open-code program. Please assign this issue to me.

**Comment by tejas-44** [comment]
> I am a participant in the open-code program. Please assign this issue to me.

Hey I have assigned this issue to you. Once done create a pull request and attach a screenshot of the changes made.
