### ISSUE TITLE
Change the buttons of the index page

### ISSUE THREAD

**Issue by tejas-44** [tejas-44/sdg-fypm-final#2]
Use CSS and implement beautiful buttons instead of the default buttons by sticking to the color scheme of the website. Add hover effect and animation to the button.

**Comment by Laurie-38** [comment]
Hey ! I try to do it :)

**Comment by tejas-44** [comment]
> Hey ! I try to do it :)


Great work but why don't you try registering in OpenCode? The registration is completely free and there are lot of stuff like certificates and goodies in the room for participants..!
You can register through the registration form at the official website:
https://csirait.in/opencode/

**Comment by surjyaneeh** [comment]
@tejas-44  I am a participant in the open-code program. Please assign this issue to me.

**Comment by tan1shk** [comment]
@tejas-44 Can you please assign me this issue?

**Comment by tejas-44** [comment]
> @tejas-44 Can you please assign me this issue?

Hello @tan1shk,
Ig you've already registered to the OpenCode event. I'll assign you this issue, create a pull request once done. Happy Contributing!
