### ISSUE TITLE
Change the font of the text in submission module

### ISSUE THREAD

**Issue by tejas-44** [tejas-44/sdg-fypm-final#3]
Change the font of the text in the submission module from default to Arial. Submission module is given as sub.html in the html folder.

**Comment by Yuji-Itadorii** [comment]
Hey, @tejas-44 I would like to work on it please assign this issue to me.

**Comment by tejas-44** [comment]
> Hey, @tejas-44 I would like to work on it please assign this issue to me.

Hey if you are registered as a participant at https://csirait.in/opencode/
you must have got a mail where there is the discord invite for the OpenCode server, there you will get all the announcement.
If you have any doubts related to any issues of this project, we can chat in the text channel allotted to this project there in the discord sever.
Moreover I think the contribution phase starts from tomorrow..

**Comment by Yuji-Itadorii** [comment]
> > Hey, @tejas-44 I would like to work on it please assign this issue to me.
> 
> Hey if you are registered as a participant at https://csirait.in/opencode/ you must have got a mail where there is the discord invite for the OpenCode server, there you will get all the announcement. If you have any doubts related to any issues of this project, we can chat in the text channel allotted to this project there in the discord sever. Moreover I think the contribution phase starts from tomorrow..

I haven't registered for any type of Open source program. I just found this issue while searching.

**Comment by tejas-44** [comment]
> > > Hey, @tejas-44 I would like to work on it please assign this issue to me.
> > 
> > 
> > Hey if you are registered as a participant at https://csirait.in/opencode/ you must have got a mail where there is the discord invite for the OpenCode server, there you will get all the announcement. If you have any doubts related to any issues of this project, we can chat in the text channel allotted to this project there in the discord sever. Moreover I think the contribution phase starts from tomorrow..
> 
> I haven't registered for any type of Open source program. I just found this issue while searching.

Then why don't you try registering and then contributing to this issue? The registration is completely free and there are lot of stuff like certificates and goodies in the room for participants..!

**Comment by Yuji-Itadorii** [comment]
> > > > Hey, @tejas-44 I would like to work on it please assign this issue to me.
> > > 
> > > 
> > > Hey if you are registered as a participant at https://csirait.in/opencode/ you must have got a mail where there is the discord invite for the OpenCode server, there you will get all the announcement. If you have any doubts related to any issues of this project, we can chat in the text channel allotted to this project there in the discord sever. Moreover I think the contribution phase starts from tomorrow..
> > 
> > 
> > I haven't registered for any type of Open source program. I just found this issue while searching.
> 
> Then why don't you try registering and then contributing to this issue? The registration is completely free and there are lot of stuff like certificates and goodies in the room for participants..!

Yeah, I just registered on the website that you mention above. Thanks for the information 😄

**Comment by Yuji-Itadorii** [comment]
Hey @tejas-44, Please assign me this issue under the OpenCode event.

**Comment by Yuji-Itadorii** [comment]
@tejas-44, Thank you for assigning me this issue.
I have resolved the issue and sent a pull request please review and merge it and also let me know if there are any mistakes you found. 😃

**Comment by tejas-44** [comment]
> @tejas-44, Thank you for assigning me this issue. I have resolved the issue and sent a pull request please review and merge it and also let me know if there are any mistakes you found. 😃

Merged your contribution, Great Work and keep contributing!
