### ISSUE TITLE
Align the form inputs.

### ISSUE THREAD

**Issue by tejas-44** [tejas-44/sdg-fypm-final#4]
The form inputs in the sub.html file are misaligned, align. Align them in a straight line.

**Comment by Sixtinebs** [comment]
Hi !
I will work on this one :)

**Comment by tejas-44** [comment]
> Hi ! I will work on this one :)

Great work but why don't you try registering in OpenCode? The registration is completely free and there are lot of stuff like certificates and goodies in the room for participants..!
You can register through the registration form at the official website:
https://csirait.in/opencode/

**Comment by Aniket-508** [comment]
@tejas-44 Can you please assign me this issue?

**Comment by tejas-44** [comment]
> @tejas-44 Can you please assign me this issue?

Hello Aniket,
Thank You for your interest in this issue, I have assigned you. Work on it and notify me I'll merge your code then! Happy Contributing.
