### ISSUE TITLE
Change image size

### ISSUE THREAD

**Issue by tejas-44** [tejas-44/sdg-fypm-final#5]
In the evaluation module, the image resolution appears to be incorrect. Adjust the picture resolution in the eval.html file to your liking so that the image looks good.

**Comment by Yuji-Itadorii** [comment]
hey @tejas-44, I am a participant in the open-code program. Please assign this issue to me.

**Comment by tejas-44** [comment]
> hey @tejas-44, I am a participant in the open-code program. Please assign this issue to me.

Hello Abhay, sorry to say but we're currently assigning one issue at a time. Once you complete your previously assigned issue I will assign this to you.

**Comment by surjyaneeh** [comment]
I am a participant in the open-code program. Please assign this issue to me.

**Comment by tejas-44** [comment]
> I am a participant in the open-code program. Please assign this issue to me.

Yep assigned, Happy Contributing!

**Comment by surjyaneeh** [comment]
> > I am a participant in the open-code program. Please assign this issue to me.
> 
> Yep assigned, Happy Contributing!

@tejas-44, 
I have resolved the issue and sent a pull request. Please review and merge it and also let me know if there are any mistakes.
